version: "2.0"
# Author: Haoji Liu
services:
  web:
    build: ./web_server
    ports:
      # nginx listens to port 80
      - "8080:80"
      # Supervisor http access
      - "9001:9001"
      - "30080:8080"
      - "30081:8081"
    links:
      - grpc
      - ftp
      - db
    # So that wysiwyg
    volumes:
      - ./web_server/src:/srv/src
    container_name: cmpe275_web
    tty: true
  db:
    ports:
      - "28017:28017"
      - "27017:27017"
      - "30180:8080"
      - "30181:8081"
    build: ./database_node
    container_name: cmpe275_db
    tty: true
