version: "3"
# Author: Haoji Liu
services:
  web:
    build: ./web_server
    ports:
      # nginx listens to port 80
      - "8080:80"
      # Supervisor http access
      - "9001:9001"
      # write port for other nodes to reach
      - "8081:8081"
    links:
      - task_scheduler
      - db
    # So that wysiwyg
    volumes:
      - ./web_server/src:/srv/src
    container_name: cmpe275_web
    tty: true
  db:
    volumes:
      - ./database_node/src:/srv/src
    build: ./database_node
    container_name: cmpe275_db
    tty: true
  task_scheduler:
    ports:
      - "9002:9002" # supervisord
      - "8082:80" # monitor
      - "5559:5559" # read client port
      - "5560:5560" # read worker port
    # So that wysiwyg
    volumes:
      - ./task_scheduler/src:/srv/src
    build: ./task_scheduler
    container_name: cmpe275_task_scheduler
    tty: true
